language: csharp
solution: Nerdle.AutoConfig.sln
install:
  - nuget restore Nerdle.AutoConfig.sln
  - nuget install NUnit.Runners -Version 2.6.4 -OutputDirectory testrunner
script:
  - xbuild /p:Configuration=Release Nerdle.AutoConfig.sln
  - mono ./testrunner/NUnit.Runners.2.6.4/tools/nunit-console.exe ./Nerdle.AutoConfig.Tests.Unit/bin/Release/Nerdle.AutoConfig.Tests.dll
  - mono ./testrunner/NUnit.Runners.2.6.4/tools/nunit-console.exe ./Nerdle.AutoConfig.Tests.Integration/bin/Release/Nerdle.AutoConfig.Tests.Integration.dll